experiment:
  backend: pytorch

  data_config:
    strategy: fixed
#    train_path: ../data/{0}/train.tsv
#    test_path: ../data/{0}/test.tsv
#    validation_path: ../data/{0}/val.tsv
    train_path: ../data/{0}/train_new.tsv
    test_path: ../data/{0}/test_new.tsv
    validation_path: ../data/{0}/valid_new.tsv

  dataset: amazon-cds

  top_k: 20
  evaluation:
    cutoffs: 20
    simple_metrics: [Recall, nDCGRendle2020]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.FPSR:
      meta:
        verbose: True
        save_recs: False
        validation_rate: 2
      epochs: 2
      batch_size: 64
      eigen_dim: 256
      l_w: 0.2
      rho: 5000
      w_1: 0.5
      w_2: 5.0
      eta: 1.0
      eps: 4e-3
      tau: 0.3
      seed: 2026
