experiment:
  backend: pytorch

  data_config:
    strategy: fixed
#    train_path: ../data/{0}/train.tsv
#    test_path: ../data/{0}/test.tsv
#    validation_path: ../data/{0}/val.tsv
    train_path: ../data/{0}/train_new.tsv
    test_path: ../data/{0}/test_new.tsv
    validation_path: ../data/{0}/valid_new.tsv

  dataset: yelp2018

  top_k: 50
  evaluation:
    cutoffs: [5, 10, 20, 50]
    simple_metrics: [Recall, nDCGRendle2020]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.FPSR:
      meta:
        verbose: True
        save_recs: False
        validation_rate: 2
      #lr: 0.001
      epochs: 2
      batch_size: 64
      eigen_dim: 256
      l_w: 0.5
      rho: 10000
      w_1: 0.6
      w_2: 2.0
      eta: 0.1
      eps: 4e-3
      tau: 0.3
      seed: 2026
