experiment:
  backend: pytorch

  data_config:
    strategy: fixed
#    train_path: ../data/{0}/train.tsv
#    test_path: ../data/{0}/test.tsv
#    validation_path: ../data/{0}/val.tsv
    train_path: ../data/{0}/train_new.tsv
    test_path: ../data/{0}/test_new.tsv
    validation_path: ../data/{0}/valid_new.tsv

  dataset: facebook_books

  top_k: 20
  evaluation:
    cutoffs: [10, 20]
    simple_metrics: [Recall, nDCGRendle2020]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.FPSR:
      meta:
        verbose: False
        save_recs: False
        validation_rate: 2
      #lr: 0.001
      epochs: 2
      batch_size: 2048
      eigen_dim: 256
      l_w: [0.1, 0.2, 0.3, 0.4, 0.5]
      rho: [100, 500, 1000, 5000, 10000]
      w_1: [0.1, 0.2, 0.5, 1, 2, 5]
      w_2: [0.1, 0.2, 0.5, 1, 2, 5]
      eta: [0.01, 0.1, 1.0]
      eps: 5e-3
      tau: [0.1, 0.2, 0.3, 0.4, 0.5]
      seed: 2026