experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    validation_path: ../data/{0}/val.tsv
    test_path: ../data/{0}/test.tsv
  dataset: facebook_book
  top_k: 50
  evaluation:
    cutoffs: [50]
    simple_metrics: [nDCGRendle2020]
  gpu: -1
  external_models_path: ../external/models/__init__.py
  models:
    external.FPSR:
      meta:
        verbose: True
        save_recs: True
        validation_rate: 2
      lr: 0.001
      epochs: 2
      factors: 64
      batch_size: 1
      eigen_n: 256
      l_w: 0.2
      rho: 5000
      theta_1: 0.5
      theta_2: 5.0
      eta: 1.0
      eps: 4e-3
      tau: 0.3
      # n_layers: 1
      seed: 123