experiment:

  backend: pytorch

  data_config:
    strategy: fixed
    train_path: ../data/{0}/train_gde.tsv
    test_path: ../data/{0}/test_gde.tsv

  dataset: gowalla_gde
  top_k: 20
  evaluation:
    cutoffs: [10,20]
    simple_metrics: [Recall, nDCG]

  gpu: 0
  external_models_path: ../external/models/__init__.py

  models:
    external.GDE:
      meta:
        save_recs: False
        verbose: True
      batch_size: 256
      factors: 64
      l_w: 0.01
      feature_type: smoothed
      smooth_ratio: 0.1
      rough_ratio: 0.0
      epochs: 160
      lr: 0.03
      dropout: 0.1
      beta: 5.0
      loss_type: adaptive
      seed: 42