experiment:

  backend: pytorch

  data_config:
    strategy: fixed
    train_path: ../data/{0}/train_gde.tsv
    test_path: ../data/{0}/test_gde.tsv

  dataset: ml-1m-gde
  top_k: 20
  evaluation:
    cutoffs: [10,20]
    simple_metrics: [Recall, nDCG]

  gpu: 0
  external_models_path: ../external/models/__init__.py

  models:
    external.GDE:
      meta:
        save_recs: False
        verbose: True
      batch_size: 256
      factors: 64
      l_w: 0.01
      feature_type: both
      smooth_ratio: 0.05
      rough_ratio: 0.005
      epochs: 300
      lr: 7.5
      dropout: 0.5
      beta: 4.0
      loss_type: adaptive
      seed: 42