experiment:
  backend: pytorch

  data_config:
    strategy: fixed
#    train_path: ../data/{0}/train.tsv
#    test_path: ../data/{0}/test.tsv
#    validation_path: ../data/{0}/val.tsv
    train_path: ../data/{0}/train_new.tsv
    test_path: ../data/{0}/test_new.tsv
    validation_path: ../data/{0}/valid_new.tsv

  dataset: gowalla

  top_k: 20
  evaluation:
    cutoffs: [10, 20]
    simple_metrics: [Recall, nDCGRendle2020]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.SVDGCNFPSR:
      meta:
        verbose: False
        save_recs: False
        validation_rate: 2
      # parameters for SVD-GCN
      epochs: 15
      batch_size: 64
      factors: 64
      lr: 7.0
      l_w: 0.01
      coef_u: 0.5
      coef_i: 0.7
      alpha: 3.0
      beta: 2.0
      req_vec: 60
      seed: 123

      # parameters for FPSR
      batch_size_2: 64
      eigen_dim: 256
      l_w_2: 0.5
      rho: 5000
      w_1: 0.2
      w_2: 5.0
      eta: 0.01
      eps: 5e-3
      tau: 0.4
      # seed: 2026
