experiment:
  backend: pytorch

  data_config:
    strategy: fixed
#    train_path: ../data/{0}/train.tsv
#    test_path: ../data/{0}/test.tsv
#    validation_path: ../data/{0}/val.tsv
    train_path: ../data/{0}/train_new.tsv
    test_path: ../data/{0}/test_new.tsv
    validation_path: ../data/{0}/valid_new.tsv

  dataset: gowalla

  top_k: 20
  evaluation:
    cutoffs: [10, 20]
    simple_metrics: [Recall, nDCGRendle2020]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.SVDGCN:
      meta:
        verbose: False
        save_recs: False
        validation_rate: 2
      epochs: 15
      batch_size: 256
      factors: 64
      lr: 9.0
      l_w: 0.01
      coef_u: 0.5
      coef_i: 0.9
      alpha: 3.0
      beta: 2.0
      req_vec: 90
      seed: 123
